// Complete recipe index from brotdoc.com/rezepte-a-bis-z/
// ~370 recipes covering all letters A-Z
const RECIPE_INDEX = [
  // A
  { name: "Alpenroggenbrot I", url: "https://brotdoc.com/2015/05/26/alpenroggenbrot-i/" },
  { name: "Alpenroggenbrot II", url: "https://brotdoc.com/2015/06/11/alpenroggenbrot-ii/" },
  { name: "Altbrot-Stangen", url: "https://brotdoc.com/2015/06/27/altbrot-stangen/" },
  { name: "Altbrot-Toastbrot", url: "https://brotdoc.com/2015/08/23/altbrot-toastbrot/" },
  { name: "Altöttinger Mühlenbrot", url: "https://brotdoc.com/2014/11/26/altottinger-muhlenbrot/" },
  { name: "Apfel-Stuten", url: "https://brotdoc.com/2019/04/04/apfel-stuten/" },
  { name: "Aromatische Weizen-Baguettes", url: "https://brotdoc.com/2012/03/19/aromatische-weizen-baguettes/" },
  { name: "Aroma-Pide", url: "https://brotdoc.com/2017/07/08/aroma-pide/" },
  { name: "Artisan-Brot von Mein Schiff", url: "https://brotdoc.com/2018/08/26/artisan-brot-von-mein-schiff/" },
  { name: "Artisan-Brot 2.0", url: "https://brotdoc.com/2018/10/20/artisan-brot-2-0/" },
  { name: "Auffrisch-Brot", url: "https://brotdoc.com/2017/08/27/auffrisch-brot/" },
  { name: "Auffrisch-Brötchen", url: "https://brotdoc.com/2017/09/30/auffrisch-broetchen/" },
  { name: "Auffrisch-Brot II", url: "https://brotdoc.com/2017/09/09/auffrisch-brot-ii/" },
  // B
  { name: "Bagels", url: "https://brotdoc.com/2025/10/05/bagels/" },
  { name: "Baguettes mit kalter Stückgare", url: "https://brotdoc.com/2014/05/06/baguettes-mit-kalter-stuckgare/" },
  { name: "Baguettes mit Poolish und langer kalter Führung", url: "https://brotdoc.com/2014/12/02/baguettes-mit-poolish-und-langer-kalter-fuhrung/" },
  { name: "Baguettes mit Poolish – neues Rezept", url: "https://brotdoc.com/2014/04/01/baguettes-mit-poolish-neues-rezept/" },
  { name: "Baguettes nach Sébastien Mauvieux", url: "https://brotdoc.com/2013/01/20/baguettes-nach-sebastien-mauvieux-frankreichs-baguette-backer-2012/" },
  { name: "Baguette au pâtes solides", url: "https://brotdoc.com/2016/09/04/baguette-au-pates-solides/" },
  { name: "Baguette Française", url: "https://brotdoc.com/2013/10/13/baguette-francaise/" },
  { name: "Baguette mit Lievito madre", url: "https://brotdoc.com/2014/03/24/baguette-mit-lievito-madre/" },
  { name: "Baguette nach Dietmar Kappl", url: "https://brotdoc.com/2020/04/25/baguette-a-la-maitre-dietmar/" },
  { name: "Baguette Rustique", url: "https://brotdoc.com/2013/07/02/baguette-rustique/" },
  { name: "Baguette-Brötchen", url: "https://brotdoc.com/2012/04/03/baguette-brotchen/" },
  { name: "Baguette-Brötchen mit Biga und langer kalter Führung", url: "https://brotdoc.com/2012/07/21/baguette-brotchen-mit-biga-und-langer-kalter-fuhrung/" },
  { name: "Basmati-Brötchen", url: "https://brotdoc.com/2019/02/24/basmati-broetchen/" },
  { name: "Beginner-Weißbrot", url: "https://brotdoc.com/2013/03/13/beginner-weisbrot/" },
  { name: "Belaugte Bierstangen", url: "https://brotdoc.com/2023/05/18/belaugte-bierstangen/" },
  { name: "Beluga-Linsenbrot I + II", url: "https://brotdoc.com/2019/05/12/beluga-linsenbrot-i-ii/" },
  { name: "Berliner Ballen", url: "https://brotdoc.com/2016/02/08/berliner-ballen/" },
  { name: "Berliner Knüppel / Schrippe", url: "https://brotdoc.com/2014/09/24/berliner-knuppel-schrippe/" },
  { name: "Bierbrot", url: "https://brotdoc.com/2018/01/21/bierbrot/" },
  { name: "Bigabrot", url: "https://brotdoc.com/2017/03/31/bigabrot/" },
  { name: "Biga Baguette", url: "https://brotdoc.com/2024/11/02/biga-baguette/" },
  { name: "Biga-Brot (neu)", url: "https://brotdoc.com/2023/08/28/biga-brot-neu/" },
  { name: "Bio-Apfelbrot", url: "https://brotdoc.com/2013/06/05/bio-apfelbrot/" },
  { name: "Bio-Baguettes", url: "https://brotdoc.com/2014/06/03/bio-baguettes/" },
  { name: "Bio-Bauernbrot", url: "https://brotdoc.com/2019/03/10/bio-bauernbrot/" },
  { name: "Blütenbrot", url: "https://brotdoc.com/2016/02/28/bluetenbrot/" },
  { name: "Blütenbrötchen", url: "https://brotdoc.com/2012/08/18/blutenbrotchen-fruhstucksbrotchen-mit-langer-kalter-fuhrung/" },
  { name: "Bolo do Caco", url: "https://brotdoc.com/2022/07/31/bolo-do-caco/" },
  { name: "Bordeaux-Brötchen", url: "https://brotdoc.com/2018/07/12/bordeaux-broetchen-muensterlaender-urstoffe/" },
  { name: "Börde-Brot", url: "https://brotdoc.com/2019/04/15/boerde-brot/" },
  { name: "Borkenberger Kloben", url: "https://brotdoc.com/2012/12/16/borkenberger-kloben/" },
  { name: "Brezel / Pretzel", url: "https://brotdoc.com/2018/11/02/brezel-pretzel/" },
  { name: "Brioche Burger-Buns", url: "https://brotdoc.com/2017/09/03/brioche-burger-buns/" },
  { name: "Brioche nach Jeffrey Hamelman", url: "https://brotdoc.com/2012/11/10/brioche-nach-jeffrey-hamelman/" },
  // C
  { name: "Casseler", url: "https://brotdoc.com/2016/07/01/casseler/" },
  { name: "Ciabatta mit Biga", url: "https://brotdoc.com/2012/06/11/ciabatta-mit-biga/" },
  { name: "Ciabatta al Farro", url: "https://brotdoc.com/2014/01/28/ciabatta-al-farro/" },
  { name: "Ciabatta mit Poolish", url: "https://brotdoc.com/2013/09/28/ciabatta-mit-poolish/" },
  { name: "Cinquecento", url: "https://brotdoc.com/2020/10/03/cinquecento/" },
  { name: "Croissants nach Jeffrey Hamelman", url: "https://brotdoc.com/2012/12/23/croissants-nach-jeffrey-hamelman/" },
  // D
  { name: "Dänisches Roggenbrot", url: "https://brotdoc.com/2016/08/14/daenisches-roggenbrot/" },
  { name: "Dänisches Sauerteigbrot", url: "https://brotdoc.com/2021/12/03/daenisches-sauerteigbrot/" },
  { name: "Das 5-Minuten-Brot", url: "https://brotdoc.com/2018/05/20/das-5-minuten-brot/" },
  { name: "Das Landbrot", url: "https://brotdoc.com/2013/04/01/das-landbrot/" },
  { name: "Das perfekte Toastbrot", url: "https://brotdoc.com/2016/06/05/das-perfekte-toastbrot/" },
  { name: "Dinkelbrot mit Kürbis", url: "https://brotdoc.com/2015/10/18/dinkelbrot-mit-kurbis/" },
  { name: "Dinkelbrot mit Ruchmehl", url: "https://brotdoc.com/2018/02/11/dinkelbrot-mit-ruchmehl/" },
  { name: "Dinkelbrot mit Walnüssen", url: "https://brotdoc.com/2012/11/25/dinkelbrot-mit-walnussen/" },
  { name: "Dinkel-Dreikorn", url: "https://brotdoc.com/2022/05/22/dinkel-dreikorn/" },
  { name: "Dinkel-Hafer-Brot", url: "https://brotdoc.com/2013/08/25/dinkel-hafer-brot/" },
  { name: "Dinkelmilchbrot", url: "https://brotdoc.com/2019/06/16/dinkelmilchbrot/" },
  { name: "Dinkel-Quark-Brot", url: "https://brotdoc.com/2018/04/01/dinkel-quark-brot/" },
  { name: "Dinkel-Roggen-Sauerteigbrot", url: "https://brotdoc.com/2014/10/07/dinkel-roggen-sauerteigbrot/" },
  { name: "Dinkel-Sandwich-Brot", url: "https://brotdoc.com/2021/05/16/dinkel-sandwich-brot/" },
  { name: "Dinkel-Seelen", url: "https://brotdoc.com/2019/08/11/dinkel-seelen/" },
  { name: "Dinkel-Toast", url: "https://brotdoc.com/2015/10/04/dinkelbrot-toastbrot-aus-dinkel/" },
  { name: "Dinkel-Vollkornbrot", url: "https://brotdoc.com/2014/08/18/dinkel-vollkornbrot/" },
  // E
  { name: "Einkornbrot mit Sauerteig", url: "https://brotdoc.com/2018/09/23/einkornbrot-mit-sauerteig/" },
  { name: "Emmer-Brot", url: "https://brotdoc.com/2015/02/01/emmer-brot/" },
  { name: "Englisches Toastbrot", url: "https://brotdoc.com/2015/07/05/englisches-toastbrot/" },
  { name: "Erdnussbrot", url: "https://brotdoc.com/2016/12/04/erdnussbrot/" },
  // F
  { name: "Fenchelbrot", url: "https://brotdoc.com/2013/07/28/fenchelbrot/" },
  { name: "Fit-Brot", url: "https://brotdoc.com/2013/10/27/fit-brot/" },
  { name: "Fladenbrot", url: "https://brotdoc.com/2013/03/24/fladenbrot/" },
  { name: "Focaccia", url: "https://brotdoc.com/2012/07/08/focaccia/" },
  { name: "Focaccia mit Poolish", url: "https://brotdoc.com/2022/06/26/focaccia-mit-poolish/" },
  { name: "Frankenlaib", url: "https://brotdoc.com/2013/05/11/frankenlaib/" },
  { name: "Frankenwecken", url: "https://brotdoc.com/2016/03/27/frankenwecken/" },
  { name: "Frühstücks-Brötchen mit Übernachtgare", url: "https://brotdoc.com/2023/02/26/fruehstuecks-broetchen-mit-uebernachtgare/" },
  // G
  { name: "Gerstenbrot", url: "https://brotdoc.com/2019/12/15/gerstenbrot/" },
  { name: "Glutenfreies Brot", url: "https://brotdoc.com/2014/09/01/glutenfreies-brot/" },
  { name: "Graubrot mit Poolish", url: "https://brotdoc.com/2013/09/14/graubrot-mit-poolish/" },
  // H
  { name: "Haferbrot", url: "https://brotdoc.com/2013/08/11/haferbrot/" },
  { name: "Haferflocken-Brötchen", url: "https://brotdoc.com/2012/09/23/haferflocken-brotchen/" },
  { name: "Hamburger Buns", url: "https://brotdoc.com/2016/05/22/hamburger-buns/" },
  { name: "Handbrot", url: "https://brotdoc.com/2021/07/11/handbrot/" },
  { name: "Hartweizen-Baguette", url: "https://brotdoc.com/2019/11/24/hartweizen-baguette/" },
  { name: "Hausbrot", url: "https://brotdoc.com/2022/09/25/hausbrot/" },
  { name: "Hefezopf", url: "https://brotdoc.com/2017/04/08/hefezopf/" },
  { name: "Helles Landbrot", url: "https://brotdoc.com/2021/09/19/helles-landbrot/" },
  { name: "Herzhaftes Flechtbrot", url: "https://brotdoc.com/2020/01/19/herzhaftes-flechtbrot/" },
  { name: "Holzofenbrot", url: "https://brotdoc.com/2014/08/03/holzofenbrot/" },
  { name: "Honig-Dinkel-Brot", url: "https://brotdoc.com/2015/09/06/honig-dinkel-brot/" },
  // I
  { name: "Irisches Sodabrot", url: "https://brotdoc.com/2013/11/10/irisches-sodabrot/" },
  { name: "Italienisches Weißbrot", url: "https://brotdoc.com/2012/05/14/italienisches-weisbrot/" },
  // J
  { name: "Joghurt-Brot", url: "https://brotdoc.com/2021/04/18/joghurt-brot/" },
  { name: "Joghurt-Dinkel-Brot", url: "https://brotdoc.com/2016/11/06/joghurt-dinkel-brot/" },
  { name: "Joghurt-Weizenmischbrot", url: "https://brotdoc.com/2013/05/26/joghurt-weizenmischbrot/" },
  // K
  { name: "Kaiserbrötchen", url: "https://brotdoc.com/2012/09/09/kaiserbrotchen/" },
  { name: "Kamutbrot", url: "https://brotdoc.com/2016/09/18/kamutbrot/" },
  { name: "Kartoffelbrot", url: "https://brotdoc.com/2012/10/07/kartoffelbrot/" },
  { name: "Kartoffel-Roggen-Brot", url: "https://brotdoc.com/2018/06/10/kartoffel-roggen-brot/" },
  { name: "Kastenbrot mit Vollkornanteil", url: "https://brotdoc.com/2020/08/09/kastenbrot-mit-vollkornanteil/" },
  { name: "Kernen-Brot", url: "https://brotdoc.com/2013/11/24/kernen-brot/" },
  { name: "Knäckebrot", url: "https://brotdoc.com/2017/01/29/knaeckebrot/" },
  { name: "Knoten-Brötchen mit Sauerteig", url: "https://brotdoc.com/2021/10/24/knoten-broetchen-mit-sauerteig/" },
  { name: "Kochstück-Brot", url: "https://brotdoc.com/2014/07/21/kochstuck-brot/" },
  { name: "Körner-Roggen-Brot", url: "https://brotdoc.com/2021/01/24/koerner-roggen-brot/" },
  { name: "Krustenbrot mit Poolish", url: "https://brotdoc.com/2013/06/23/krustenbrot-mit-poolish/" },
  { name: "Kürbisbrot", url: "https://brotdoc.com/2013/10/13/kurbisbrot/" },
  { name: "Kürbiskernbrot", url: "https://brotdoc.com/2017/10/08/kuerbiskernbrot/" },
  // L
  { name: "Laugenbrötchen", url: "https://brotdoc.com/2015/03/29/laugenbroetchen/" },
  { name: "Laugenstangen", url: "https://brotdoc.com/2013/02/03/laugenstangen/" },
  { name: "Leinsamen-Dinkel-Brot", url: "https://brotdoc.com/2015/06/14/leinsamen-dinkel-brot/" },
  { name: "Leinsamenbrot", url: "https://brotdoc.com/2016/10/09/leinsamenbrot/" },
  { name: "Levain Brot", url: "https://brotdoc.com/2020/06/07/levain-brot/" },
  { name: "Lievito Madre Brot", url: "https://brotdoc.com/2022/01/02/lievito-madre-brot/" },
  // M
  { name: "Malzbrot", url: "https://brotdoc.com/2015/04/26/malzbrot/" },
  { name: "Mischbrot mit Roggenanteil", url: "https://brotdoc.com/2012/04/22/mischbrot-mit-roggenanteil/" },
  { name: "Mischbrot mit Sauerteig", url: "https://brotdoc.com/2013/01/06/mischbrot-mit-sauerteig/" },
  { name: "Mischbrot mit Weizen und Roggen", url: "https://brotdoc.com/2013/11/03/mischbrot-mit-weizen-und-roggen/" },
  { name: "Mohnstriezel", url: "https://brotdoc.com/2016/01/10/mohnstriezel/" },
  { name: "Münsterländer Graubrot", url: "https://brotdoc.com/2020/02/16/muensterlaender-graubrot/" },
  { name: "Muss-weg-Brot", url: "https://brotdoc.com/2020/11/07/muss-weg-brot/" },
  // N
  { name: "Nussbrot", url: "https://brotdoc.com/2013/09/01/nussbrot/" },
  { name: "Nuss-Honig-Brot", url: "https://brotdoc.com/2020/03/22/nuss-honig-brot/" },
  // O
  { name: "Olivenbrot", url: "https://brotdoc.com/2013/04/14/olivenbrot/" },
  { name: "Osterbrot", url: "https://brotdoc.com/2015/03/22/osterbrot/" },
  // P
  { name: "Pain de Campagne", url: "https://brotdoc.com/2012/06/25/pain-de-campagne/" },
  { name: "Pain de Campagne mit Poolish", url: "https://brotdoc.com/2014/07/07/pain-de-campagne-mit-poolish/" },
  { name: "Pan Brioche", url: "https://brotdoc.com/2022/03/27/pan-brioche/" },
  { name: "Pan de Cristal", url: "https://brotdoc.com/2021/11/28/pan-de-cristal/" },
  { name: "Panettone", url: "https://brotdoc.com/2022/12/04/panettone/" },
  { name: "Pane di Como", url: "https://brotdoc.com/2017/02/26/pane-di-como/" },
  { name: "Pane Toscano", url: "https://brotdoc.com/2013/05/05/pane-toscano/" },
  { name: "Pitta-Brot", url: "https://brotdoc.com/2013/02/17/pitta-brot/" },
  { name: "Pizza-Teig", url: "https://brotdoc.com/2015/08/09/pizza-teig/" },
  { name: "Prinzenbrot", url: "https://brotdoc.com/2018/12/09/prinzenbrot/" },
  // Q
  { name: "Quark-Brot", url: "https://brotdoc.com/2015/11/08/quark-brot/" },
  // R
  { name: "Roggenbrot 50/50", url: "https://brotdoc.com/2012/03/04/roggenbrot-50-50/" },
  { name: "Roggenbrot mit Brühstück", url: "https://brotdoc.com/2013/12/22/roggenbrot-mit-bruhstuck/" },
  { name: "Roggenbrot mit Roggenvollkornmehl", url: "https://brotdoc.com/2012/05/28/roggenbrot-mit-roggenvollkornmehl/" },
  { name: "Roggen-Sauerteig-Brot", url: "https://brotdoc.com/2013/07/14/roggen-sauerteig-brot/" },
  { name: "Roggenvollkornbrot", url: "https://brotdoc.com/2014/02/17/roggenvollkornbrot/" },
  { name: "Roggenvollkornbrot 100%", url: "https://brotdoc.com/2015/12/27/roggenvollkornbrot-100/" },
  { name: "Rosinen-Walnuss-Brot", url: "https://brotdoc.com/2016/03/06/rosinen-walnuss-brot/" },
  { name: "Rosmarin-Olivenöl-Brot", url: "https://brotdoc.com/2018/03/18/rosmarin-olivenoel-brot/" },
  { name: "Ruchbrot", url: "https://brotdoc.com/2017/05/28/ruchbrot/" },
  // S
  { name: "Saalachtaler Kaisersemmeln", url: "https://brotdoc.com/2013/08/27/saalachtaler-kaisersemmeln/" },
  { name: "Saatenkraftbrot", url: "https://brotdoc.com/2023/07/08/saatenkraftbrot/" },
  { name: "Saaten-Blüten", url: "https://brotdoc.com/2016/01/16/saaten-blueten/" },
  { name: "Saaten-Ecken", url: "https://brotdoc.com/2012/10/10/saaten-ecken/" },
  { name: "Saaten-Kasten", url: "https://brotdoc.com/2018/02/25/saaten-kasten/" },
  { name: "Saaten-Kraftbrot", url: "https://brotdoc.com/2012/06/02/saaten-kraftbrot/" },
  { name: "Saaten-Weißbrot", url: "https://brotdoc.com/2012/03/29/saaten-weisbrot/" },
  { name: "Saaten-Brot", url: "https://brotdoc.com/2014/11/10/saaten-brot/" },
  { name: "Saaten-65er", url: "https://brotdoc.com/2017/10/29/saaten-65er/" },
  { name: "Saaten-812er", url: "https://brotdoc.com/2016/02/13/saaten-812er/" },
  { name: "Saatlinge", url: "https://brotdoc.com/2015/09/12/saatlinge/" },
  { name: "Saftiger Christstollen", url: "https://brotdoc.com/2013/01/06/saftiger-christstollen/" },
  { name: "Saftiges Graubrot", url: "https://brotdoc.com/2023/04/16/saftiges-graubrot/" },
  { name: "Saftiges Kürbisbrot", url: "https://brotdoc.com/2012/11/01/saftiges-kurbisbrot/" },
  { name: "Saftiges Rosinenbrot", url: "https://brotdoc.com/2014/12/09/saftiges-rosinenbrot/" },
  { name: "Saftkorn-Brot", url: "https://brotdoc.com/2013/05/18/saftkorn-brot/" },
  { name: "Sandwichbrot mit Emmer-Vollkorn", url: "https://brotdoc.com/2016/03/31/sandwichbrot-mit-emmer-vollkorn/" },
  { name: "Sandwich-Brote: Buttermilch-Brot", url: "https://brotdoc.com/2014/09/10/sandwich-brote-buttermilch-brot/" },
  { name: "Sandwich-Brote: Dunkles Sandwichbrot", url: "https://brotdoc.com/2014/09/18/sandwich-brote-dunkles-sandwichbrot/" },
  { name: "Sandwich-Brote: Kamut-Leinsamen-Brot", url: "https://brotdoc.com/2014/10/08/sandwich-brote-kamut-leinsamen-brot/" },
  { name: "Sandwich-Brote: Sahnestuten", url: "https://brotdoc.com/2014/10/22/sandwich-brote-sahnestuten/" },
  { name: "Sauerteig-Baguette", url: "https://brotdoc.com/2012/02/19/sauerteig-baguette/" },
  { name: "Sauerteig-Brötchen", url: "https://brotdoc.com/2016/04/10/sauerteig-brotchen/" },
  { name: "Sauerteig-Mischbrot", url: "https://brotdoc.com/2012/08/05/sauerteig-mischbrot/" },
  { name: "Sauerteig-Pide", url: "https://brotdoc.com/2015/07/18/sauerteig-pide/" },
  { name: "Sauerteig-Pizza", url: "https://brotdoc.com/2020/08/02/sauerteig-pizza/" },
  { name: "Sauerteig-Toastbrot", url: "https://brotdoc.com/2013/05/15/sauerteig-toastbrot/" },
  { name: "Sauerteigbrot mit Dinkelvollkorn", url: "https://brotdoc.com/2017/11/12/sauerteigbrot-mit-dinkelvollkorn/" },
  { name: "Scheunenlaib", url: "https://brotdoc.com/2016/04/17/scheunenlaib/" },
  { name: "Schleifen-Brötchen", url: "https://brotdoc.com/2019/10/03/schleifen-broetchen/" },
  { name: "Schmalzbrot", url: "https://brotdoc.com/2015/02/10/schmalzbrot/" },
  { name: "Schnelle Sonntagsbrötchen", url: "https://brotdoc.com/2022/11/27/schnelle-sonntagsbroetchen-auffrischrezept/" },
  { name: "Schneller Einback", url: "https://brotdoc.com/2022/03/05/schneller-einback-als-zeilensemmel/" },
  { name: "Schülerbrot", url: "https://brotdoc.com/2016/05/29/schuelerbrot/" },
  { name: "Schwäbische Dinkel-Seelen", url: "https://brotdoc.com/2012/05/08/schwabische-dinkel-seelen/" },
  { name: "Schwarzbrot (Grundrezept)", url: "https://brotdoc.com/2020/01/12/schwarzbrot-grundrezept/" },
  { name: "Schwarzes Roggenbrot", url: "https://brotdoc.com/2015/01/18/schwarzes-roggenbrot/" },
  { name: "Schweizer Bürli", url: "https://brotdoc.com/2017/03/06/schweizer-buerlis/" },
  { name: "Schweizer Zopf", url: "https://brotdoc.com/2013/04/21/schweizer-zopf/" },
  { name: "Sehnsuchtbrot", url: "https://brotdoc.com/2017/01/09/sehnsuchtbrot/" },
  { name: "Semolakruste", url: "https://brotdoc.com/2024/05/12/semolakruste/" },
  { name: "Semola Deluxe", url: "https://brotdoc.com/2023/02/19/semola-deluxe/" },
  { name: "Semolinabrot", url: "https://brotdoc.com/2017/05/18/semolinabrot/" },
  { name: "Seniorenbrot", url: "https://brotdoc.com/2016/06/28/seniorenbrot/" },
  { name: "Sesambrötchen", url: "https://brotdoc.com/2013/11/03/sesambrotchen-sesame-seed-rolls/" },
  { name: "Sesamkruste", url: "https://brotdoc.com/2012/10/28/sesamkruste/" },
  { name: "Sesamstuten", url: "https://brotdoc.com/2019/03/17/sesamstuten/" },
  { name: "Silvester-Focaccia", url: "https://brotdoc.com/2021/01/01/silvester-focaccia/" },
  { name: "Simit", url: "https://brotdoc.com/2025/10/26/simit/" },
  { name: "Sommerbrot 2018", url: "https://brotdoc.com/2018/07/17/sommerbrot-2018/" },
  { name: "Sonnenblumenbrötchen", url: "https://brotdoc.com/2014/01/29/sonnenblumenbrotchen-sunflower-rolls/" },
  { name: "Sonnenblumenbrot", url: "https://brotdoc.com/2013/11/16/sonnenblumenbrot-sunflower-seed-bread/" },
  { name: "Sonnenblumen-Kernlinge", url: "https://brotdoc.com/2015/04/03/sonnenblumen-kernlinge/" },
  { name: "Sonnenblumen-Saatenbrot", url: "https://brotdoc.com/2013/05/09/sonnenblumen-saatenbrot/" },
  { name: "Sonnenblumen-Sesamstangen", url: "https://brotdoc.com/2013/02/10/sonnenblumen-sesamstangen/" },
  { name: "Sonnenblumen-Stuten", url: "https://brotdoc.com/2016/09/25/sonnenblumen-stuten/" },
  { name: "Sonnenblumenkernbrot", url: "https://brotdoc.com/2013/03/10/sonnenblumenkernbrot/" },
  { name: "Sonntagsbrot", url: "https://brotdoc.com/2016/08/28/sonntagsbrot/" },
  { name: "Sonntagscroissants", url: "https://brotdoc.com/2016/02/21/sonntagscroissants/" },
  { name: "Starkbier-Mohnzopf", url: "https://brotdoc.com/2013/06/19/starkbier-mohnzopf/" },
  { name: "Steirisches Kürbiskernbrot", url: "https://brotdoc.com/2014/03/10/steirisches-kurbiskernbrot/" },
  { name: "Steinberg-Kanten", url: "https://brotdoc.com/2016/06/05/steinberg-kanten/" },
  { name: "Steinmetz-Brot", url: "https://brotdoc.com/2018/10/07/steinmetz-brot/" },
  { name: "Steinmühlenbrot (Tourte de Meule)", url: "https://brotdoc.com/2024/10/06/steinmuehlenbrot-tourte-de-meule/" },
  { name: "Stutenkerl", url: "https://brotdoc.com/2015/12/05/stutenkerl/" },
  { name: "Subway Brot", url: "https://brotdoc.com/2020/05/16/subway-brotstangen/" },
  { name: "Süddeutsches Weizenmischbrot", url: "https://brotdoc.com/2012/02/05/suddeutsches-weizenmischbrot/" },
  { name: "Südpfälzer Landbrot", url: "https://brotdoc.com/2013/07/17/sudpfalzer-landbrot/" },
  { name: "Süße Himbeer-Focaccia", url: "https://brotdoc.com/2019/05/05/suesse-himbeer-foccacia/" },
  { name: "Sylter Weißbrot nach Alexander Klutzny", url: "https://brotdoc.com/2024/10/22/sylter-weissbrot-nach-alexander-klutzny/" },
  { name: "Sythener Joghurt-Stuten", url: "https://brotdoc.com/2012/01/27/sythener-joghurt-stuten/" },
  { name: "Sythener Landbrot", url: "https://brotdoc.com/2012/09/13/sythener-landbrot/" },
  // T
  { name: "Tarte au Sucre", url: "https://brotdoc.com/2023/05/28/tarte-au-sucre/" },
  { name: "Tiger-Brot", url: "https://brotdoc.com/2020/07/05/tiger-brot/" },
  { name: "Tiger-Stangen", url: "https://brotdoc.com/2020/11/01/tiger-stangen/" },
  { name: "Toastbrot", url: "https://brotdoc.com/2012/02/15/toastbrot/" },
  { name: "Toastbrot mit Poolish", url: "https://brotdoc.com/2016/10/23/toastbrot-mit-poolish/" },
  { name: "Toskanisches Weißbrot", url: "https://brotdoc.com/2015/04/12/toskanisches-weisbrot/" },
  { name: "Tourte de Meule Deluxe", url: "https://brotdoc.com/2022/05/20/tourte-de-meule-deluxe/" },
  { name: "Traditionelles Pide", url: "https://brotdoc.com/2015/06/18/traditionelles-pide/" },
  { name: "Traditionsbrot", url: "https://brotdoc.com/2019/05/18/traditionsbrot/" },
  { name: "Türkisches Fladenbrot", url: "https://brotdoc.com/2022/09/15/tuerkisches-fladenbrot-grundrezept/" },
  // U
  { name: "Ur-Brot", url: "https://brotdoc.com/2019/12/01/ur-brot/" },
  { name: "Ur-Dreikornbrot", url: "https://brotdoc.com/2015/11/07/ur-dreikornbrot/" },
  { name: "Urkornbrot", url: "https://brotdoc.com/2016/06/19/urkornbrot/" },
  { name: "Urlaubsbrot", url: "https://brotdoc.com/2022/08/21/urlaubsbrot/" },
  { name: "Urgetreide-Vollkornbrot", url: "https://brotdoc.com/2013/03/01/urkorn-vollkornbrot/" },
  { name: "Urstoff-Baguette", url: "https://brotdoc.com/2018/09/23/urstoff-baguette/" },
  { name: "Urstoff-Brot I", url: "https://brotdoc.com/2018/08/29/urstoff-brot-i/" },
  { name: "Urstoff-Brot II", url: "https://brotdoc.com/2018/09/17/urstoff-brot-ii/" },
  // V
  { name: "Verruchtes Bierbrot", url: "https://brotdoc.com/2020/11/21/verruchtes-bierbrot/" },
  { name: "Vielpfünder Dattellaib", url: "https://brotdoc.com/2019/12/14/vierpfuender-dattellaib/" },
  { name: "Vielsaaten-Brötchen", url: "https://brotdoc.com/2014/08/27/vielsaaten-brotchen-und-betrachtungen-zur-entspannung/" },
  { name: "Vinschgauer Paarl", url: "https://brotdoc.com/2016/07/10/vinschgauer-paarl/" },
  { name: "Vinschger Fladenbrote", url: "https://brotdoc.com/2015/08/09/vinschger-fladenbrote/" },
  { name: "Vollkornbrot Sylter Art", url: "https://brotdoc.com/2024/12/31/vollkornbrot-sylter-art/" },
  { name: "Vollkorn-Baguette", url: "https://brotdoc.com/2017/06/25/vollkorn-baguette/" },
  { name: "Vollkorn-Dinkelbrötchen", url: "https://brotdoc.com/2011/12/23/vollkorn-dinkelbrotchen/" },
  { name: "Vollkorn-Dinkel-Brot", url: "https://brotdoc.com/2014/10/20/vollkorn-dinkel-brot/" },
  { name: "Vollkorn-Kommissbrot", url: "https://brotdoc.com/2013/03/10/vollkorn-kommissbrot/" },
  { name: "Vollkorn-Pide", url: "https://brotdoc.com/2015/05/19/vollkorn-pide/" },
  { name: "Vollkorn-Sandwichbrot", url: "https://brotdoc.com/2018/04/26/vollkorn-sandwichbrot/" },
  { name: "Vollkorn-Sauerteigbrot", url: "https://brotdoc.com/2014/01/12/vollkorn-sauerteigbrot/" },
  { name: "Vollkorn-Sauerteigbrot Populationsweizen", url: "https://brotdoc.com/2023/10/02/vollkorn-sauerteigbrot-populationsweizen/" },
  { name: "Vollkorn-Soft-Rolls", url: "https://brotdoc.com/2022/01/30/vollkorn-soft-rolls/" },
  { name: "Vollkorn-Toastbrot", url: "https://brotdoc.com/2013/01/10/vollkorn-toastbrot/" },
  { name: "Vollkorn-Toastbrot (neu)", url: "https://brotdoc.com/2022/07/03/vollkorn-toastbrot-neu/" },
  { name: "Vollkorn-Weizenbrötchen", url: "https://brotdoc.com/2013/06/09/vollkorn-weizenbroetchen/" },
  { name: "Vollkornbrot mit Körnern", url: "https://brotdoc.com/2020/11/15/vollkornbrot-mit-koernern/" },
  { name: "Vollwert-Kanten", url: "https://brotdoc.com/2016/08/28/vollwert-kanten/" },
  { name: "Vollwert-Laib", url: "https://brotdoc.com/2021/10/03/vollwert-laib/" },
  { name: "Von-Hand-Brot", url: "https://brotdoc.com/2019/03/23/von-hand-brot/" },
  // W
  { name: "Weiße Brötchen", url: "https://brotdoc.com/2019/04/07/weisse-broetchen/" },
  { name: "Weißbrot mit Kochstück", url: "https://brotdoc.com/2014/04/14/weisbrot-mit-kochstuck/" },
  { name: "Weihnachts-Stollen", url: "https://brotdoc.com/2012/11/18/weihnachts-stollen/" },
  { name: "Weizen-Hirse Brot", url: "https://brotdoc.com/2026/02/01/weizen-hirse-brot/" },
  { name: "Weizen-Roggen-Sauerteigbrot", url: "https://brotdoc.com/2022/04/03/weizen-roggen-sauerteigbrot/" },
  { name: "Weizen-Sauerteigbrot", url: "https://brotdoc.com/2013/08/04/weizen-sauerteigbrot/" },
  { name: "Weizen-Schwarzbrot", url: "https://brotdoc.com/2013/09/14/urweizen-schwarzbrot/" },
  { name: "Weizen-Toasties", url: "https://brotdoc.com/2022/05/04/weizen-toasties/" },
  { name: "Weizen-Würzbrot", url: "https://brotdoc.com/2018/06/09/weizen-wuerzbrot/" },
  { name: "Weizenbrot mit Butter", url: "https://brotdoc.com/2021/02/21/weizenbrot-mit-butter/" },
  { name: "Weizenbrot mit Lievito Madre", url: "https://brotdoc.com/2022/10/30/weizenbrot-mit-lievito-madre/" },
  { name: "Weizenmischbrot 80/20", url: "https://brotdoc.com/2015/08/30/weizenmischbrot-80-20/" },
  { name: "Weizensauerteig-Batard", url: "https://brotdoc.com/2017/07/23/weizensauerteig-batard/" },
  { name: "Weizensauerteig-Wecken", url: "https://brotdoc.com/2014/02/24/weizensauerteig-wecken-sourdough-buns/" },
  { name: "Weizentoast Weiß / Vollkorn", url: "https://brotdoc.com/2023/01/14/weizentoast-weiss-vollkorn/" },
  { name: "Weizenvollkornbrot", url: "https://brotdoc.com/2015/05/10/weizenvollkornbrot/" },
  { name: "Westfalenstolz", url: "https://brotdoc.com/2022/02/06/westfalenstolz-haeussler-nova/" },
  { name: "Westfalen-Kruste", url: "https://brotdoc.com/2013/12/23/westfalen-kruste-westphalia-crust/" },
  { name: "Westruper Bauernbrot", url: "https://brotdoc.com/2013/02/06/westruper-bauernbrot/" },
  { name: "White-Wholewheat-Bread", url: "https://brotdoc.com/2016/11/02/white-wholewheat-bread/" },
  { name: "Winterbrot", url: "https://brotdoc.com/2018/11/25/winterbrot/" },
  { name: "Wit Brood – Niederländischer Kastenstuten", url: "https://brotdoc.com/2012/07/26/wit-brood-niederlandischer-kastenstuten/" },
  { name: "World-Bread-Day Weizensauer-Kruste", url: "https://brotdoc.com/2018/10/16/world-bread-day-weizensauer-kruste/" },
  { name: "Wriezener Roggenvollkornbrot", url: "https://brotdoc.com/2013/01/30/wriezener-roggenvollkornbrot/" },
  { name: "Würziger Dinkellaib", url: "https://brotdoc.com/2014/07/01/wurziger-dinkellaib/" },
  { name: "Würzige Käsebrötchen", url: "https://brotdoc.com/2024/05/22/wuerzige-kaesebroetchen/" },
  { name: "Würzige Sesamkruste", url: "https://brotdoc.com/2011/12/30/wurzige-sesamkruste/" },
  // Z + #
  { name: "24-Stunden-Baguettes", url: "https://brotdoc.com/2018/03/18/24-stunden-baguettes/" },
  { name: "48-Stunden-Baguettes", url: "https://brotdoc.com/2017/11/01/48-stunden-baguettes/" },
  { name: "48-Stunden-Baguettes (neu)", url: "https://brotdoc.com/2022/10/23/48-stunden-baguettes-neu/" },
  { name: "7-Pfünder Hausbrot", url: "https://brotdoc.com/2012/11/30/7-pfunder-hausbrot/" },
  { name: "Zimtschnecken", url: "https://brotdoc.com/2016/12/18/zimtschnecken/" },
  { name: "Zopf", url: "https://brotdoc.com/2021/08/22/zopf/" },
  { name: "Zwiebelbrot", url: "https://brotdoc.com/2015/07/19/zwiebelbrot/" },
  { name: "Zwiebelbrötchen", url: "https://brotdoc.com/2018/09/09/zwiebelbroetchen/" },
];
